Removed GlobalRegistry from registry.go
ossf/criticality_score pull request #316
Opened 2023-01-30 15:59 UTC by nathannaveen

Removed the `GlobalRegisty` variable from `internal/scorer/algorithm/registry.go` because it isn't good practice to use global variables. I was able to remove `GlobalRegistry` because the only places any function in `registry.go` was being used was in `wam.go` and `config.go`.

The `Register()` function (From `registry.go`) was only being used in the `init()` function (From `wam.go`). The `NewALgorithm()` function (From `registry.go`) was only being used in the `Algorithm()` function (From `config.go`). Since those were the only places any function from `registry.go` was being used externaly I created a `NewRegistry()` in `Algorithm()` and then registered it, and returned `r.NewAlgorithm()`.

Because of creating a `NewRegistry()` and registering it in `Algorithm` I removed the `init()` function in `wam.go` because it wasn't being used. I also removed the `Register()` and `NewAlgorithm()` functions from `registry.go` because they weren't being used. I also removed `GlobalRegisty`.

Signed-off-by: nathannaveen <42319948+nathannaveen@users.noreply.github.com>

2023-01-30 22:41 UTC, calebbrown commented
Thanks Nathan! This change generally looks good, just one minor nit.

2023-01-31 14:41 UTC, nathannaveen commented
Hi Caleb, thanks for the review. Just wanted to double check, did you add the nit to it?

2023-01-31 21:34 UTC, calebbrown requested changes

2023-01-31 21:35 UTC, calebbrown commented
> Hi Caleb, thanks for the review. Just wanted to double check, did you add the nit to it?

🤦 woops, the "pending" tag is very easy to miss. Added now.

2023-01-31 22:05 UTC, calebbrown approved these changes

2023-01-31 22:14 UTC, merged